import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Firebase configuration and initialization
class FirebaseConfig {
  FirebaseConfig._();

  /// Initialize Firebase
  /// 
  /// This method initializes Firebase for the app.
  /// On mobile platforms (Android/iOS), it automatically reads configuration
  /// from `google-services.json` (Android) or `GoogleService-Info.plist` (iOS).
  /// 
  /// For web, Firebase options need to be provided manually.
  static Future<void> initialize() async {
    try {
      if (kIsWeb) {
        // For web, Firebase options need to be provided
        // You can either use FirebaseConfig from firebase_options.dart (generated by FlutterFire CLI)
        // or provide options manually
        await Firebase.initializeApp(
          options: const FirebaseOptions(
            apiKey: 'YOUR_API_KEY',
            appId: 'YOUR_APP_ID',
            messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
            projectId: 'YOUR_PROJECT_ID',
            // Add other required fields based on your Firebase project
          ),
        );
      } else {
        // For mobile platforms (Android/iOS), Firebase automatically reads
        // from google-services.json or GoogleService-Info.plist
        await Firebase.initializeApp();
      }
      
      if (kDebugMode) {
        debugPrint('✅ Firebase initialized successfully');
      }
    } catch (e) {
      if (kDebugMode) {
        debugPrint('⛔ Firebase initialization failed');
        debugPrint('Error: $e');
      }
      
      // Re-throw to let the app handle the error
      // The app won't work without Firebase, so it's better to fail early
      rethrow;
    }
  }
}

